name: Start Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the next release (e.g. 1.0.0)
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: main
      - name: Setup Node.js Environment
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Add Release Branch
        env:
          VERSION: ${{ inputs.version }}
        run: bash scripts/release.sh add_release_branch "$VERSION"
